sudo: false
language: java
jdk: oraclejdk8
cache:
        directories:
        - $HOME/.m2/repository

services: mysql

before_install:
        # workaround, see https://github.com/travis-ci/travis-ci/issues/4629
        - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

# install dependencies
install: mvn dependency:go-offline -B -V

before_script:
        # initalize empty database and privileges 
        - mysql -uroot -e "CREATE DATABASE stevedb;" -v
        - mysql -uroot -e "GRANT ALL PRIVILEGES ON stevedb.* TO 'steve'@'localhost' IDENTIFIED BY 'changeme';" -v
        - mysql -uroot -e "GRANT SELECT ON mysql.proc TO 'steve'@'localhost' IDENTIFIED BY 'changeme';" -v

# start the actual build
script: mvn clean package -B -V
