sudo: false
language: java
jdk: oraclejdk8
cache:
        directories:
        - $HOME/.m2

services: mysql

before_install:
        - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
        - mysql -uroot -e "CREATE DATABASE stevedb;"
        - mysql -uroot -e "GRANT ALL PRIVILEGES ON stevedb.* TO 'steve'@'localhost' IDENTIFIED BY 'changeme';"
        - mysql -uroot -e "GRANT SELECT ON mysql.proc TO 'steve'@'localhost' IDENTIFIED BY 'changeme';"

script:
        mvn clean package
